name: DeskHero CI/CD

on:
  push:
    branches: [ master ]
  workflow_dispatch:  # Pozwala na ręczne uruchomienie

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Konfiguracja JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      
      - name: Nadanie uprawnień dla gradlew
        working-directory: ./backend
        run: chmod +x ./gradlew
      
      - name: Testowanie backendu
        working-directory: ./backend
        run: ./gradlew test
  
  build:
    needs: backend-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Konfiguracja JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      
      - name: Nadanie uprawnień dla gradlew
        working-directory: ./backend
        run: chmod +x ./gradlew
      
      - name: Konfiguracja Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Build backend
        working-directory: ./backend
        run: ./gradlew bootJar
      
      - name: Instalacja zależności frontend
        working-directory: ./frontend
        run: npm ci
      
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
      
      - name: Zachowanie artefaktów
        uses: actions/upload-artifact@v4
        with:
          name: application-build
          path: |
            backend/build/libs/*.jar
            frontend/dist/ 
